name: Update keys.txt

on:
  workflow_dispatch: null

jobs:
  update:
    name: Update keys.txt
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup NodeJS environment
        uses: actions/setup-node@v4
        with:
          node-version: 14
          cache: npm

      - name: Install dependencies
        run: npm install axios simple-git

      - name: Get keys
        run: |
          npm run getkeys2

      - name: Checkout keys branch
        uses: actions/checkout@v4
        with:
          ref: appkeys
          path: appkeys_repo

      - name: Update key.txt if it differs
        run: |
          file=key.txt
          cd appkeys_repo
          echo "Old -> $(cat $file) || New -> $(cat ../$file)"
          if [[ "$(cat $file)" != "$(cat ../$file)" ]]; then
            cp ../$file .
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add $file
            git commit --amend -m "chore: Updating key.txt"
            git push --force
          fi

  # Workaround for CI schedule event, to prevent its delays (5min ~ 1h!)
  retrigger:
    name: Retrigger workflow
    runs-on: ubuntu-latest
    if: '${{ always() }}'
    needs:
      - update
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Retrigger workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Update keys.txt
          token: '${{ secrets.PAT_GITHUB }}'
          retain_days: 0
          keep_minimum_runs: 10
