name: Fetch and Format Rabbitstream Keys from API

on:
  push:
    branches:
      - main

jobs:
  fetch-rabbitstream-keys:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch keys from API and format
      run: |
        curl -s https://keys4.fun/ | jq '[.rabbitstream.keys[] | [.[]]]' > keys
        
    - name: Commit changes
      run: |
        git config --global user.email "blacksourcellc@gmail.com"
        git config --global user.name "blacksourcellc"
        git add keys
        git commit -m "Update and format Rabbitstream keys from API"
        git push origin main
