name: Update keys

on:
  workflow_dispatch: null

jobs:
  update:
    name: Update keys
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup NodeJS environment
        uses: actions/setup-node@v4
        with:
          node-version: 14
          cache: npm

      - name: Install dependencies
        run: npm install axios simple-git

      - name: Get keys and push to keys branch
        run: npm run getkeys

# Workaround for CI schedule event, to prevent its delays (5min ~ 1h!)
retrigger:
  name: Retrigger workflow
  runs-on: ubuntu-latest
  if: '${{ always() }}'
  needs:
    - update
  steps:
    - name: Clone repo
      uses: actions/checkout@v3
      with:
        ref: main
    - name: Retrigger workflow
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Update keys
        token: '${{ secrets.PAT_GITHUB }}'
